fn main() {
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed=tauri.conf.json");
    // Declaring the app commands makes tauri-build auto-generate
    // `permissions/autogenerated/allow-*.toml` files for each command.
    // Without them, the app's ACL manifest has no entries for the commands,
    // and Tauri REJECTS every invoke coming from a remote origin
    // (https://www.tiktok.com) with "Command ... not allowed by ACL".
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&["jump_to_external"]),
    ))
    .expect("failed to run tauri-build");
}
